name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "yonatangr86@gmail.com"
          git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/YonatanG86/simple-java-maven-app.git

      # Step 3: Debug Git Remote
      - name: Debug Git Remote
        run: git remote -v

      # Step 4: Bump Maven Version
      - name: Bump Maven Version
        uses: phips28/gh-action-bump-maven-version@v2
        id: bump_version
        with:
          type: patch # Can be major, minor, or patch
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      # Step 5: Prepare Maven Release
      - name: Prepare Maven Release
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_TOKEN }}
        run: |
          mvn release:prepare \
            -DreleaseVersion=${{ steps.bump_version.outputs.new_version }} \
            -DdevelopmentVersion=${{ steps.bump_version.outputs.new_version }}-SNAPSHOT \
            -Dusername=${GIT_USERNAME} \
            -Dpassword=${GIT_PASSWORD} \
            -DscmCommentPrefix="[Release] " \
            -B

      # Step 6: Perform Maven Release
      - name: Perform Maven Release
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_TOKEN }}
        run: |
          mvn release:perform -Darguments="-DskipDeploy=true" -B

      # Step 7: Build the application
      - name: Build with Maven
        run: mvn clean package

      # Step 8: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 9: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:latest

      # Step 10: Deploy and Test
      - name: Deploy and Test
        run: |
          CONTAINER_ID=$(docker run -d ygsol86/simple-java-maven-app:latest)
          sleep 2
          if docker logs $CONTAINER_ID | grep -q "Hello World!"; then
            echo "Application printed 'Hello World!' successfully."
          else
            docker logs $CONTAINER_ID
            exit 1
          fi
          docker stop $CONTAINER_ID
          docker rm $CONTAINER_ID
