name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java and Maven
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.17.0

      # Step 3: Increment the Patch Version
      - name: Increment version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          PATCH=$(echo $CURRENT_VERSION | awk -F. '{print $3+1}')
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1"."$2}')".$PATCH"
          mvn versions:set -DnewVersion=$NEW_VERSION
          mvn versions:commit
          echo "Updated version to: $NEW_VERSION"

      # Step 4: Build the application
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ygsol86/simple-java-maven-app:latest .

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ygsol86/simple-java-maven-app:latest

      # Step 8: Deploy and Test
      - name: Deploy with Docker
        run: |
          docker run -d -p 8080:8080 ygsol86/simple-java-maven-app:latest
          sleep 10
          curl -f http://localhost:8080
