name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Bump Maven Version
      - name: Bump Maven Version
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1.0.0

      # Step 3: Build the application
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:latest

      # Step 6: Deploy and Test
      - name: Deploy and Test
        run: |
          CONTAINER_ID=$(docker run -d ygsol86/simple-java-maven-app:latest)
          sleep 2
          if docker logs $CONTAINER_ID | grep -q "Hello World!"; then
            echo "Application printed 'Hello World!' successfully."
          else
            docker logs $CONTAINER_ID
            exit 1
          fi
          docker stop $CONTAINER_ID
          docker rm $CONTAINER_ID
