name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug - Verify workspace files
      - name: Verify workspace files
        run: ls -R

      # Step 3: Set up Java and Maven
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.17.0

      # Step 4: Increment the Patch Version
      - name: Increment version
        id: version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          PATCH=$(echo $CURRENT_VERSION | awk -F. '{print $3+1}')
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1"."$2}')".$PATCH"
          mvn versions:set -DnewVersion=$NEW_VERSION
          mvn versions:commit
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      # Step 5: Build the application
      - name: Build with Maven
        run: mvn clean package

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-java-maven-app:latest

      # Step 8: Deploy and Test
      - name: Deploy and Test
        run: |
          docker run -d -p 8080:8080 ygsol86/simple-java-maven-app:latest
          for i in {1..10}; do
            if curl -f http://localhost:8080; then
              echo "Application is up and running"
              exit 0
            fi
            echo "Waiting for application to start..."
            sleep 5
          done
          echo "Application failed to start"
          exit 1
